### ISSUE TITLE
need update

### ISSUE THREAD

**Issue by Automatic123** [japnimedev/Complicated-Cheat#2]
waiting for update boss. araw araw ako nag vivisit sau <3

**Comment by japnimedev** [comment]
@Automatic123 aww someone pa pala is update here, i'll update this again dont worry. If I closed this thread, it means I've updated it.

**Comment by Automatic123** [comment]
thank you so much. im your number one fan since lumabas ito sa symb na follow na kita hanggang dito. hehe. im still amazed <3

**Comment by japnimedev** [comment]
![image](https://user-images.githubusercontent.com/29234610/46900756-e4ffe200-ced9-11e8-8b29-a7246209c257.png)

Closer to releasement.

**Comment by japnimedev** [comment]
Closed for the official released.

**Comment by Automatic123** [comment]
Thank you so much lalo na sa new features recoil control the best!
